### DISCUSSION TITLE
TOC doesn't work on my post.

### DISCUSSION THREAD

**Discussion by mendax1234** [academicpages/academicpages.github.io#2099] [Q&A]
I try to add toc to my post and here is my code below:
```
layout: single
title:  "Harvard CS50 Week2 Summary"
header:
  image: posts/Harvard_CS50.png
  teaser: posts/Harvard_CS50.png
categories: 
  - Harvard-CS50
tags:
  - C
toc: true
toc_sticky: true
```
But seems that it doesn't work. Can someone help me with it? Thanks!
