### DISCUSSION TITLE
How to edit mobile page

### DISCUSSION THREAD

**Discussion by Jaewoo97** [academicpages/academicpages.github.io#2118] [Q&A]
Hello,

Could you provide a brief description on how to edit the mobile page layout? 

I would like the page layout (figure size, etc) to be different when accessed with computer and with mobile.

Thanks for a greate template!

Best,
Jaewoo

**Comment by rjzupkoii** [comment]
The template uses responsive web design so a lot of it is structured so that it really doesn't try to determine if you are using a computer or mobile device, but rather looks at the size of the screen you are using. In a couple places you can [find code like the following](https://github.com/academicpages/academicpages.github.io/blob/7525c7342e7cf982196e8efed676f10c617f9049/_sass/_sidebar.scss#L16):

```scss
  @media screen and (min-width: $sidebar-screen-min-width) {
    height: 100vh;
    overflow-y: auto;               // Add scrollbar if the sidebar is too long
    position: fixed;
    padding-top: $masthead-height;
  }
```

Which is explicitly checking that you are using a screen ([as opposed to print or speech](https://www.w3schools.com/cssref/css3_pr_mediaquery.php)) and that the screen is at least a configured width before adding a scrollbar to the sidebar. There's also some code involved with the top menu, but for the most part, very little of the template attempts to distinguish based upon the screen size.
