### DISCUSSION TITLE
Docker Builds without style

### DISCUSSION THREAD

**Discussion by DemoySegment** [academicpages/academicpages.github.io#2608] [Q&A]
Hi all. I am trying to build it locally with Docker using the exact commands in the tutorial. But my built version is missing the styles. I don't why it is happening. Also, all the links in this built version are directed to 0.0.0.0:port instead of localhost:port. Any insight will be helpful. Thanks!
<img width="1920" alt="Snipaste_2024-11-16_13-46-53" src="https://github.com/user-attachments/assets/b08f7b02-3184-49dd-a771-cd230e5a0528">
<img width="660" alt="Snipaste_2024-11-16_13-47-45" src="https://github.com/user-attachments/assets/f0ba483c-fde4-4f13-b9f2-6a743c71402f">

**Comment by saykind** [comment]
I experience the same issue.

**Reply by runboyuu** [reply]
Exactly the same.

**Comment by rjzupkoii** [comment]
I haven't worked with the Docker container that much, but usually when this issue occurs it's due to an issue with the `_config.yml` file and where Jekyll is looking for the files. Something to check might be that the `baseurl` setting makes sense for working inside of the container.

**Reply by mtillman14** [reply]
I'm having the same problem. The baseurl is "" in the _config.yml. Any solutions to this?

**Comment by alejandro-mahillo** [comment]
I ran into the same issue and I’m happy to share that I managed to solve it by adding an extra config file specifically for Docker and slightly modifying my `docker-compose.yml`. 🙌

### ✅ Step 1: Add a new config file

Create a file called `_config_docker.yml` with this line:

```yml
url: ""
```

### ✅ Step 2: Update your `docker-compose.yml`

Make sure your `docker-compose.yml` looks like this:

```yaml
services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes: [ .:/usr/src/app ]
    ports: [ 4000:4000 ]
    environment: [JEKYLL_ENV=docker]
    user: 1000:1000
    command: jekyll serve --host 0.0.0.0 -w --config _config.yml,_config_docker.yml
```

The key part is adding the extra config file to the `command` section and setting the environment variable.

This idea came from a super helpful [Stack Overflow post](https://stackoverflow.com/questions/57933583/broken-urls-in-jekyll-in-docker?rq=2) — huge thanks to the folks over there! 🙏

Hope this helps someone else! 😊
