### ISSUE TITLE
Is it possible to justify the text in blog posts?

### ISSUE THREAD

**Issue by SreenivasVRao** [academicpages/academicpages.github.io#151]
It's aligned with the left margin, but not the right. Would be nice if it was justified.

**Comment by jmloyola** [comment]
In case you are still looking for the answer, you have to edit the file `_sass/_page.scss`.
Add `text-align: justify;` to the `.page__content` block. It should look something like this:

```css
.page__content {

  text-align: justify;
```

I've done it in this [commit](https://github.com/jmloyola/jmloyola.github.io/commit/da67f90ad21a201a2f27a2eab612d58b940fe557) if you want to check it.

You can also justify only some tags of the html. For that, just add that line to the tag's block inside the `page__content` block.

**Comment by PhilippeGagnonPHD** [comment]
> In case you are still looking for the answer, you have to edit the file _sass/_page.scss.
> Add text-align: justify; to the .page__content block. It should look something like this:
> .page__content {
> 
>   text-align: justify;
> I've done it in this commit if you want to check it.
> You can also justify only some tags of the html. For that, just add that line to the tag's block inside the page__content block.
> @staeiou, I think this issue can be closed.

I did that and it worked for the main page. But I don't see how to also justify the text in "Talks". Do someone have an idea please?

**Comment by jmloyola** [comment]
I peaked at your blog and I think your problem might be related to the change of name in the layout of `Talks` to `News`.
Can you test going back to `Talks` and see if the text is justified?

**Comment by PhilippeGagnonPHD** [comment]
> I peaked at your blog and I think your problem might be related to the change of name in the layout of Talks to News.
> Can you test going back to Talks and see if the text is justified?

Hi! Thanks for the suggestion. I tried, but it didn't work (I left it how you recommended if you wanna see). Maybe something could be done in "archive-single-talk.html"!? Sorry, I'm not familiar with that kind of coding...

**Comment by jmloyola** [comment]
Ohh I think this time I know what might be the problem.
It seems that academicpages does not format the excerpt of the post the same way it does with the text in the post.

What you see in [this page](https://philippegagnonphd.github.io/PhilippeGagnon.github.io//talks/) are the list of all the news you have with a little excerpt. If you click on [the link](https://philippegagnonphd.github.io/PhilippeGagnon.github.io//talks/2019-08-08-Bayescomp) you access the post that go in more detail about the subject. You can see that in this last one the text **is justified**.

If I were you, I'd define the excerpt manually. Note that ([taken from here](https://mmistakes.github.io/minimal-mistakes/docs/layouts/)):
> Post and page excerpts are auto-generated by Jekyll which grabs the first paragraph of text.

To override this text with something more specific, you can use somethink like this:
```YAML
---
title: "I will present my work on nonreversible jump algorithms at Bayes Comp 2020"
collection: talks
type: # "Talk"
permalink: /talks/2019-08-08-Bayescomp
venue: "Reitz Union, University of Florida"
excerpt: 'A BRIEF SUMMARY OF THE NEWS'
date: 2020-01-07
location: "Gainesville, Florida, USA"
---
Abstract (for more information about the conference see this [website](http://users.stat.ufl.edu/~jhobert/BayesComp2020/Conf_Website/)): It is now well known that nonreversible Markov chain Monte Carlo methods often outperform their reversible counterparts. Lifting the state space (Chen et al. (1999)) has proved to be a successful technique for constructing such samplers relying on nonreversible Markov chains. The idea is to see the random variables that we wish to generate as position variables to which we associate velocity (or direction) variables, doubling the size of the state space. At each iteration of such samplers, the positions evolve deterministically as a function of the directions, and this is followed by a possible update of the latter. This direction assisted scheme may induce persistent movements that allow to traverse the state space more quickly, compared with the traditional methods producing chains with diffusive patterns. This explains the gain in efficiency. Directions playing a central role, the technique can only be employed to explore state spaces for which this concept is well defined. In this paper, we introduce samplers that we call nonreversible jump algorithms that can be applied to simultaneously achieve model selection and parameter estimation, in situations where the family of models considered forms a sequence of nested models; there thus exists a natural order among the models, and therefore, directions. These samplers are constructed by modifying reversible jump algorithms after having lifted the part of the state space associated with the model indicator. We demonstrate their correctness and show that they compare favourably to their reversible counterpart using both theoretical arguments as well as numerical experiments. We address implementation challenges, facilitating application by users.
P.S.: the preprint will soon be on ArXiv.
```
Tell me if if you are happy with the result.
