### ISSUE TITLE
default code block font-size too small

### ISSUE THREAD

**Issue by geoalchimista** [academicpages/academicpages.github.io#59]
The default code block font-size was defined as `$type-size-7` in `_sass/_syntax.scss`. This is too small compared with the normal text font.

I'd recommend changing it to `0.8125em` (~13 px), which is between `$type-size-5` (~16 px) and `$type-size-6` (~12 px).
```css
  .highlight {
    margin: 0;
    font-family: $monospace;
    font-size: .8125em;  /* was $type-size-7 */
    line-height: 1.8;
  }
```

**Comment by lightsquared** [comment]
I concur.  The code block font is about half the size of the normal text font.

**Comment by gsanroma** [comment]
I also found distracting the icons in the top-right corner of code blocks with text `f121`
Example:
<img width="199" alt="missing-icon" src="https://user-images.githubusercontent.com/20971783/54074484-30ed6200-4293-11e9-93d9-f4805df5e466.png">
Removed the icon by commenting out the line `content:` in `_sass/_syntax.scss`
```css
  &:before {
    position: absolute;
    top: 0;
    right: 0;
    padding: 0.5em;
    background-color: $lighter-gray;
    /* content: "\f121"; */
    font-family: "fontawesome" !important;
    font-size: $type-size-6;
    line-height: 1;
    text-transform: none;
    speak: none;
  }
```
